---
title: "Clases de R"
author: "Wilson Guerra"
format: html
editor: visual
editor_options: 
  chunk_output_type: inline
---
# diseños experimentales

## DCA


Dosis de fertilización nitrogenada

- 0
- 50
- 100
- 150

Rep: 5

```{r}
# Instalar el paquete agricolae si no lo tienes
# install.packages("agricolae")

# Cargar la librería agricolae
library(agricolae)

# Definir los tratamientos (niveles de fertilización nitrogenada)
tratamientos <- c(0, 50, 100, 150)

# Definir el número de repeticiones
reps <- 5

# Generar el diseño DCA
dca <- design.crd(tratamientos, reps, seed = 123)

# Mostrar el diseño generado
dca$book

# Opcional: guardar el diseño en un archivo CSV
write.csv(dca$book, file = "diseño_DCA_fertilización_5reps.csv", row.names = FALSE)




```
```{r}

# Definimos los tratamientos
tratamientos <- c(0, 50, 100, 150)

# Número de repeticiones por tratamiento
repeticiones <- 5

# Creamos una estructura de datos para el DCA
# Generamos un data frame con los tratamientos y las repeticiones
dca <- data.frame(
  Tratamiento = rep(tratamientos, each = repeticiones),
  Repeticion = rep(1:repeticiones, times = length(tratamientos))
)

# Aleatorizamos el orden de los tratamientos
set.seed(123)  # Fijamos una semilla para reproducibilidad
dca <- dca[sample(nrow(dca)), ]

# Mostramos el diseño
print(dca)

# Exportamos a un archivo CSV
write.csv(dca, file = "dca_tratamientos.csv", row.names = FALSE)




```


## DBCA

Factor 1 (dosis nitrogeno): 0, 50, 100, 150
Factor 2 (variedades de papa): canchan y peruanita
Bloques: 5

```{r}

# factorial 4 x 2 with 5 blocks
library(agricolae)
trt<-c(4,2) # factorial 4x2
outdesign <-design.ab(trt, r=4, serie=2)
book<-outdesign$book
book

head(book,10) # print of the field book
# factorial 4 x 2 x 5 with 5 replications in completely randomized design.
trt<-c(2,2,2)
outdesign<-design.ab(trt, r=5, serie=2,design="crd")
book<-outdesign$book
print(book)
# factorial 3 x 3 in latin square design.
trt <-c(3,3)
outdesign<-design.ab(trt, serie=2, design="lsd")
book<-outdesign$book
print(book)




```

```{r}
# factorial 4 x 2 with 5 blocks
library(agricolae)
trt<-c(4,2) # factorial 4x2
outdesign <-design.ab(trt, r=4, serie=2)

str(outdesign)

book<-outdesign$book
book


```




# Analisis de datos

## DBCA

Factor 1 (riego): sequia y irrigado
Factor 2 (genotipo): 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
Bloques: 5

```{r}

# factorial 2 x 15 with 5 blocks
library(agricolae)
trt<-c(2, 15) # factorial 2x15
outdesign <-design.ab(trt, r=5, serie=2)
book<-outdesign$book
book

head(book,10) # print of the field book
# factorial 2 x 15 x 5 with 5 replications in completely randomized design.
trt<-c(2,2,2)
outdesign<-design.ab(trt, r=5, serie=2,design="crd")
book<-outdesign$book
print(book)
# factorial 3 x 3 in latin square design.
trt <-c(3,3)
outdesign<-design.ab(trt, serie=2, design="lsd")
book<-outdesign$book
print(book)



```

```{r}

library(readxl)
LA_MOLINA_2014_POTATO_WUE_FB_ <- read_excel("LA MOLINA 2014 POTATO WUE (FB).xlsx", 
    sheet = "fb")
View(LA_MOLINA_2014_POTATO_WUE_FB_)





```
```{r}
modelo <- aov(formula = lfa ~ bloque + riego + geno + riego*geno, data = LA_MOLINA_2014_POTATO_WUE_FB_)


plot(modelo)


anova(modelo)




```

## Comparacion de medias

```{r}
library(agricolae)


mc <- agricolae::duncan.test(y = modelo
                             , trt = c("riego", "geno"))

mc


str(mc)

```

```{r}
library(emmeans)
library(multcomp)
library(tidyverse)

mc <- emmeans(modelo, ~ riego | geno) %>% 
  data.frame()


mc
```


## Grafico
